#!/usr/bin/env perl

use strict;
use warnings;
use autodie qw(:all);
use Data::Dumper;

# CD17/cantbans.pdf
# run pdftotext cantbans.pdf

my %churches = (
	'AND' => 'St Andrew',
	'ALP' => 'St Alphage',
	'BDN' => 'St Mary Bredin',
	'BMN' => 'St Mary Bredman',
	'CHR' => 'Christchurch',
	'DUN' => 'St Dunstan',
	'GEO' => 'St George',
	'GRY' => 'St Gregory',
	'HYX' => 'Holy Cross',
	'MAG' => 'St Mary Magdalene',
	'MIL' => 'St Mildred',
	'MRG' => 'St Margaret',
	'MTN' => 'St Martin',
	'NGT' => 'St Mary Northgate',
	'PTR' => 'St Peter',
	'PAU' => 'St Paul',
	'STS' => 'All Saints',
	'WAL' => 'Walloon Church',
);

$SIG{__WARN__} = sub { die @_ };

open(my $fin, '<', 'cantbans.txt');
my $inheader = 1;
my $mode;
my @data;
my $index = 0;
my $see = 0;
while (my $line = <$fin>) {
	chomp $line;

	if($line eq 'Name') {
		$inheader = 0;
		$mode = 'name';
		next;
	}
	next if($inheader);
	next if($line eq 'B');
	next if($line =~ /^Page \d.+\d$/);
	next if($line =~ /^/);

	if(length($line) == 0) {
		if($mode eq 'name') {
			$mode = 'date';
		} elsif($mode eq 'date') {
			$mode = 'spouse';
		} elsif($mode eq 'spouse') {
			$mode = 'church';
		}
		$index = 0;
	} elsif($line =~ /BANNS Index/i) {
		$mode = 'name';
		# print Data::Dumper->new([\@data])->Dump();
		while(my $row = shift(@data)) {
			next if($see-- && !defined($row->{'name'}));
			die Data::Dumper->new([$row])->Dump() if(keys %{$row} != 4);
			die Data::Dumper->new([$row])->Dump() if(!defined($row->{'church'}));
			if(my $church = $churches{$row->{'church'}}) {
				print "banns, ", $row->{'name'}, ', ',
					$row->{'date'}, ', ',
					$row->{'spouse'}, ', ',
					"$church\n";
			}
		}
		$index = 0;
	} else {
		if($mode eq 'name') {
			if($line =~ /^[A-Z]+\ssee\s[A-Z]+/i) {
				$see++;
				next;
			}
			$see = 0;
			$line =~ s/^\*[\s\-]+//;
			if($line =~ /^([A-Z]+)\-\-+(.+)/) {
				$data[$index++]->{'name'} = $1;
				$data[$index++]->{'name'} = $2;
				next;
			}
		} elsif($mode eq 'date') {
			if($line =~ /^(--.--.---)(--.--.---)(.+)/) {
				$data[$index++]->{'date'} = $1;
				$data[$index++]->{'date'} = $2;
				$data[$index++]->{'date'} = $3;
				next;
			}
			if($line =~ /^(--.--.---.)(.+)/) {
				$data[$index++]->{'date'} = $1;
				$data[$index++]->{'date'} = $2;
				next;
			}
			# $line =~ s/^--\.--\.---//;
		} elsif($mode eq 'spouse') {
			if($line =~ /^([\-\s?]+)([A-Z].+)$/) {
				$data[$index++]->{'spouse'} = $1;
				$data[$index++]->{'spouse'} = $2;
				next;
			}
			if($line =~ /^([A-Z]+)\s\-+([A-Z\s]+)/i) {
				$data[$index++]->{'spouse'} = $1;
				$data[$index++]->{'spouse'} = $2;
				next;
			}
		}

		if($line eq 'Name') {
			while(my $row = shift(@data)) {
				die Data::Dumper->new([$row])->Dump() if(scalar keys %{$row} != 4);
				if(my $church = $churches{$row->{'church'}}) {
					print "banns, ", $row->{'name'}, ', ',
						$row->{'date'}, ', ',
						$row->{'spouse'}, ', ',
						"$church\n";
				} else {
					die Data::Dumper->new([$row])->Dump();
				}
			}
			$mode = 'name';
			$index = 0;
		} elsif($line eq 'Date') {
			$mode = 'date';
			$index = 0;
		} elsif($line eq 'Intended Spouse') {
			$mode = 'spouse';
			$index = 0;
		} elsif($line eq 'Church') {
			$mode = 'church';
			$index = 0;
		} else {
			if(($line =~ /^\d\d\.\d\d\.\d\d\d\d$/) && ($mode ne 'date')) {
				die "$mode: $line";
				$data[$index++]->{'date'} = $line;
			} elsif(($mode eq 'date') && ($line !~ /^[\d\-\.\?\s]+\*?$/)) {
				die "$mode: $line";
			} elsif($mode eq 'abode') {
				if($line =~ /^([A-Z\s]+)\-+(.+)$/i) {
					$data[$index++]->{'abode'} = $1;
					$data[$index++]->{'abode'} = $2;
				} elsif($line =~ /^(\d+\s[YM])+\s(.+)$/) {
					$data[$index]->{'age'} = $1;
					$data[$index++]->{'abode'} = $2;
				}
			} elsif($mode eq 'church') {
				$line =~ s/^B\s//;
				if(defined($churches{$line})) {
					$data[$index++]->{'church'} = $line;
				} elsif($line =~ /^(\-\-\-?)([A-Z]{3})$/) {
					$data[$index++]->{'church'} = $1;
					$data[$index++]->{'church'} = $2;
				} elsif($line ne '---') {
					die $line;
				}
			} else {
				$data[$index++]->{$mode} = $line;
				# print "$mode: $line\n";
			}
		}
	}
}

while(my $row = shift(@data)) {
	die Data::Dumper->new([$row])->Dump() if(scalar keys %{$row} != 4);
	if(my $church = $churches{$row->{'church'}}) {
		print "banns, ", $row->{'name'}, ', ',
			$row->{'date'}, ', ',
			$row->{'spouse'}, ', ',
			"$church\n";
	} else {
		die Data::Dumper->new([$row])->Dump();
	}
}
