#!/usr/bin/env perl

use strict;
use warnings;
use autodie qw(:all);
use DBI;

use constant { DATABASE => '../kfhs.sql' };

if(-r DATABASE) {
	unlink DATABASE;
}

my $dbh = DBI->connect('dbi:SQLite:dbname=' . DATABASE, undef, undef, { RaiseError => 1, AutoCommit => 1,synchronous => 0, locking_mode => 'EXCLUSIVE' });
$dbh->do('PRAGMA cache_size = -65536');	# 64MB
$dbh->do('PRAGMA journal_mode = OFF');

$dbh->do('CREATE TABLE kfhs(entry VARCHAR, cd NUMBER, type VARCHAR, church VARCHAR, name2 VARCHAR, date VARCHAR, age CHAR(5), abode VARCHAR)');

if(open(my $pin, '-|', './Cantbap')) {
	my $sth = $dbh->prepare('INSERT INTO kfhs(cd, type, church, entry, date) VALUES(?, ?, ?, ?, ?)');
	while(my $line = <$pin>) {
		chomp $line;
		my ($type, $name, $parents, $date, $church) = split(/, /, $line);
		if($parents eq 'N.G.') {
			$parents = 'NULL';
		}
		# print "$entry->$name\n";
		$sth->execute(17, 'baptism', $church, $name, $date);
	}
	close $pin;
}

if(open(my $pin, '-|', './cantbans')) {
	my $sth = $dbh->prepare('INSERT INTO kfhs(cd, type, church, entry, name2, date) VALUES(?, ?, ?, ?, ?, ?)');
	while(my $line = <$pin>) {
		chomp $line;
		my ($type, $entry, $date, $name2, $church) = split(/, /, $line);
		# print "$entry->$name\n";
		$sth->execute(17, 'banns', $church, $entry, $name2, $date);
	}
	close $pin;
}

if(open(my $pin, '-|', './cantmar')) {
	my $sth = $dbh->prepare('INSERT INTO kfhs(cd, type, church, entry, name2, date) VALUES(?, ?, ?, ?, ?, ?)');
	while(my $line = <$pin>) {
		chomp $line;
		my ($type, $entry, $name2, $date, $church) = split(/, /, $line);
		# print "$entry->$entry\n";
		$sth->execute(17, 'marriage', $church, $entry, $name2, $date);
	}
	close $pin;
}

if(open(my $pin, '-|', './cantbur')) {
	my $sth = $dbh->prepare('INSERT INTO kfhs(cd, type, church, entry, age, date) VALUES(?, ?, ?, ?, ?, ?)');
	while(my $line = <$pin>) {
		chomp $line;
		my ($type, $entry, $date, $age, $abode, $church) = split(/, /, $line);
		if($age eq 'N.G.') {
			$age = 'NULL';
		}
		if($abode eq 'N.G.') {
			$abode = 'NULL';
		}
		# print "$entry->$name\n";
		$sth->execute(17, 'burial', $church, $entry, $age, $date);
	}
	close $pin;
}

$dbh->disconnect();
