#!/usr/bin/env perl

use strict;
use warnings;
use autodie qw(:all);
use DBI;

if(-r 'cd17.sql') {
	unlink 'cd17.sql';
}

my $dbh = DBI->connect("dbi:SQLite:dbname=cd17.sql", undef, undef, { RaiseError => 1, AutoCommit => 1,synchronous => 0, locking_mode => 'EXCLUSIVE' });
$dbh->do('PRAGMA cache_size = -65536');	# 64MB
$dbh->do('PRAGMA journal_mode = OFF');

$dbh->do('CREATE TABLE kfhs(cd CHAR(4), type VARCHAR, church VARCHAR, name1 VARCHAR, name2 VARCHAR, date VARCHAR, age CHAR(5), abode VARCHAR)');

if(open(my $pin, '-|', './Cantbap')) {
	my $sth = $dbh->prepare('INSERT INTO kfhs(cd, type, church, name1, date) VALUES(?, ?, ?, ?, ?)');
	while(my $line = <$pin>) {
		chomp $line;
		my ($entry, $name, $parents, $date, $church) = split(/, /, $line);
		if($parents eq 'N.G.') {
			$parents = 'NULL';
		}
		# print "$entry->$name\n";
		$sth->execute('CD17', 'baptism', $church, $name, $date);
	}
	close $pin;
}

if(open(my $pin, '-|', './cantbans')) {
	my $sth = $dbh->prepare('INSERT INTO kfhs(cd, type, church, name1, name2, date) VALUES(?, ?, ?, ?, ?, ?)');
	while(my $line = <$pin>) {
		chomp $line;
		my ($entry, $name1, $date, $name2, $church) = split(/, /, $line);
		# print "$entry->$name\n";
		$sth->execute('CD17', 'banns', $church, $name1, $name2, $date);
	}
	close $pin;
}

if(open(my $pin, '-|', './cantmar')) {
	my $sth = $dbh->prepare('INSERT INTO kfhs(cd, type, church, name1, name2, date) VALUES(?, ?, ?, ?, ?, ?)');
	while(my $line = <$pin>) {
		chomp $line;
		my ($entry, $name1, $name2, $date, $church) = split(/, /, $line);
		# print "$entry->$name1\n";
		$sth->execute('CD17', 'marriage', $church, $name1, $name2, $date);
	}
	close $pin;
}

if(open(my $pin, '-|', './cantbur')) {
	my $sth = $dbh->prepare('INSERT INTO kfhs(cd, type, church, name1, age, date) VALUES(?, ?, ?, ?, ?, ?)');
	while(my $line = <$pin>) {
		chomp $line;
		my ($entry, $name1, $date, $age, $abode, $church) = split(/, /, $line);
		if($age eq 'N.G.') {
			$age = 'NULL';
		}
		if($abode eq 'N.G.') {
			$abode = 'NULL';
		}
		# print "$entry->$name\n";
		$sth->execute('CD17', 'baptism', $church, $name1, $age, $date);
	}
	close $pin;
}

$dbh->disconnect();
